### ISSUE TITLE
Please don't disable the context right-click' menu

### ISSUE THREAD

**Issue by drewwills** [uPortal-contrib/esup-filemanager#47]
Bonjour la France! :fr: 

https://github.com/uPortal-contrib/esup-filemanager/blob/master/src/main/webapp/js/esup-stock.js#L1649

This code disables the right-click menu for any portal page on which the esup-filemanager appears.

As I'm sure you're aware, uPortal-start (Apereo default uPortal 5) now includes the esup-filemanager as a "bundled" portlet application.  We're also using the portlet in the default (quickstart) data.

**Comment by vbonamy** [comment]
Bonjour Drew :)
I'm OK with this, esup-filemanager doesn't have to modify the behavior of all the page (and of the others portlets), that's sure. So I'm sorry that's the case right now.
Thank you for your PR #48 that resolves this issue.
That's very cool that esup-filemanager is now in uPortal-start and so on :1st_place_medal: 
Thank you again
Vincent.
