### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by jgribonvald** [uPortal-contrib/esup-filemanager#60]
I don't know how it's work with OSS sonatype but it could be great that several peoples has rigths to publish a new release on. What do you think @vbonamy ? Could you configure it ? I think that you are the only one who can make release.

**Comment by vbonamy** [comment]
Hello Julien,
People who can publish esup-portail.org or esupportail.org packages on officials maven repositories via https://oss.sonatype.org are EsupPortail guys like me and @prigaux 
A wiki page on esup-portail.org explains what we've done : 
https://www.esup-portail.org/wiki/display/DOC/Maven
As esup-portail.org member, if you want to have rights on esup-portail.org and esupportail.org we can set your sonatype username here : https://issues.sonatype.org/browse/OSSRH-26136
But now esup-filemanager is in uPortal-contrib github repository.
So maybe we habe to modify its maven groupId to put apereo.org or whatever ?
Thank you.
Vincent.

**Comment by jgribonvald** [comment]
Thanks @vbonamy I cc to @cmurphy but I'm not sure that we need to modify anything now.

**Comment by jgribonvald** [comment]
@vbonamy could you add my username jgribonvald on oss sonatype ?

Else I rerun the last question (about to modify the groupID) to @ChristianMurphy @apetro  @bjagg @drewwills or should we discuss about it in the uPSC ?

**Comment by vbonamy** [comment]
@jgribonvald done : https://issues.sonatype.org/browse/OSSRH-26136
